export const CHANGE_DIRECTORY = "change_directory"
export const ADD_FOLDER = "add_folder"
export const DEL_FOLDER = "del_folder"
export const GO_BACK = "go_back"
export const GO_FORWARD = "go_forward"
export const SET_CURRENT_PATH = "set_current_path"
export const SET_PREVIOUS_PATH = "set_previous_path"
export const JUMP_TO_DIR = "jump_to_dir"